// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://karlo.co.id/terms",
        "contact": {
            "name": "Karlo Engineering",
            "email": "engineering@karlo.co.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalog": {
            "get": {
                "tags": [
                    "Catalog"
                ],
                "summary": "List catalogue kinds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/catalog/{kind}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "List catalogue entries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_platform_response.Meta"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Create or update a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.CatalogItem"
                        }
                    }
                }
            }
        },
        "/catalog/{kind}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Get catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.CatalogItem"
                        }
                    }
                }
            }
        },
        "/trucks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "List trucks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_platform_response.Meta"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "Create truck",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Truck"
                        }
                    }
                }
            }
        },
        "/trucks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "Get truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Truck"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "Update truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "Delete truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/trucks/{id}/drivers": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "Pair driver with truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Trucks"
                ],
                "summary": "Unpair driver from truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/warehouses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Warehouses"
                ],
                "summary": "List warehouses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_platform_response.Meta"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Warehouses"
                ],
                "summary": "Create warehouse",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Warehouse"
                        }
                    }
                }
            }
        },
        "/warehouses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Warehouses"
                ],
                "summary": "Get warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Warehouse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Warehouses"
                ],
                "summary": "Update warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Warehouses"
                ],
                "summary": "Delete warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_karlo_masterdata-service_internal_models.CatalogItem": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "code": {
                    "description": "Code is the stable business identifier, unique within a kind. Orders\nreference catalogue entries by id, but imports and integrations match on\ncode, so it must not change.",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.CatalogKind"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "description": "ParentID links hierarchical catalogues: a city to its province, a\ndistrict to its city.",
                    "type": "string"
                },
                "sortOrder": {
                    "description": "SortOrder controls presentation where the list is not alphabetical, such\nas truck sizes.",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.CatalogKind": {
            "type": "string",
            "enum": [
                "brand",
                "cargoType",
                "cargoTruckCapacity",
                "currency",
                "district",
                "item",
                "itemCharacter",
                "itemType",
                "kota",
                "paymentType",
                "pricingType",
                "provinsi",
                "rateCard",
                "requirement",
                "route",
                "truckBody",
                "truckHead",
                "truckType",
                "faq",
                "jobVacancy"
            ],
            "x-enum-varnames": [
                "KindBrand",
                "KindCargoType",
                "KindCargoTruckCapacity",
                "KindCurrency",
                "KindDistrict",
                "KindItem",
                "KindItemCharacter",
                "KindItemType",
                "KindKota",
                "KindPaymentType",
                "KindPricingType",
                "KindProvinsi",
                "KindRateCard",
                "KindRequirement",
                "KindRoute",
                "KindTruckBody",
                "KindTruckHead",
                "KindTruckType",
                "KindFaq",
                "KindJobVacancy"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.GeoPoint": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "description": "Coordinates are [longitude, latitude], which is GeoJSON order and the\nreverse of how people usually say it.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.Truck": {
            "type": "object",
            "properties": {
                "brandId": {
                    "type": "string"
                },
                "chassisNumber": {
                    "type": "string"
                },
                "companyId": {
                    "description": "CompanyID is the tenant key. Every query in this service filters on it;\na query that does not is a data leak between companies.",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "documents": {
                    "description": "Documents holds STNK, KIR and insurance records with their expiry dates.",
                    "type": "object",
                    "additionalProperties": true
                },
                "driverIds": {
                    "description": "DriverIDs are authentication-service user ids, held as strings because\nthey are UUIDs in another database, not ObjectIds here.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "engineNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isAvailable": {
                    "type": "boolean"
                },
                "policeNumber": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "truckBodyId": {
                    "type": "string"
                },
                "truckGroupId": {
                    "type": "string"
                },
                "truckHeadId": {
                    "type": "string"
                },
                "truckTypeId": {
                    "description": "These reference CatalogItem ids.",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.Warehouse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cityId": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "geofenceRadius": {
                    "description": "GeofenceRadius is in metres. The business service compares a driver's\nreported position against it when a company enables geofenced completion.",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.GeoPoint"
                },
                "name": {
                    "type": "string"
                },
                "operatingHours": {
                    "description": "OperatingHours records opening times per weekday.",
                    "type": "object",
                    "additionalProperties": true
                },
                "picName": {
                    "type": "string"
                },
                "picPhone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "provinceId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_platform_response.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "RS256 access token issued by the authentication service, as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5002",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Karlo Master Data API",
	Description:      "Reference data. Global catalogues (truck types, cargo types, cities) shared by every company, and per-company registers (trucks, warehouses, customers).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
