// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Karlo Engineering",
            "email": "engineering@karlo.co.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalog": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Catalogue kinds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers.kindInfo"
                            }
                        }
                    }
                }
            }
        },
        "/catalog/{kind}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List one catalogue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Restrict to children of this entry (e.g. sub-categories of a category)",
                        "name": "parentId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort, e.g. name:asc",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filters as field:value, comma separated",
                        "name": "filtered",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data[], meta{page,limit,totalRows,totalPages}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Karlo staff create shared entries; a company creates its own. Fields depend on the kind — see the models for each catalogue (Brand, CargoType, Item, TruckHead, TruckBody, TruckClass, Customer, VehicleGroup, TrackerModel…).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Add a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind, from GET /catalog",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entry fields for the kind",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/catalog/{kind}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Edit a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Changed fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft: documents already referencing it keep resolving; the name frees up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Retire a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/documents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "One of vehicleId or driverId is required unless expiringWithinDays is set, which sweeps the company.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "List documents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Owner vehicle",
                        "name": "vehicleId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Owner driver",
                        "name": "driverId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only documents expiring within N days",
                        "name": "expiringWithinDays",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []models.Document, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Add a document",
                "parameters": [
                    {
                        "description": "Document; exactly one of vehicleId / driverId",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.DocumentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Document"
                        }
                    }
                }
            }
        },
        "/documents/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Edit a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Changed fields; owner cannot change",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.DocumentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Document"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Delete a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/drivers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "List drivers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "active or inactive",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Name, phone or employee number",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []models.Driver, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Add a driver",
                "parameters": [
                    {
                        "description": "Driver",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.DriverInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Driver"
                        }
                    }
                }
            }
        },
        "/drivers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Get a driver",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driver id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Driver"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Edit a driver",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driver id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Changed fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.DriverInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Driver"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Retire a driver",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driver id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trackers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "List devices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "gps or dashcam",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only fitted (true) or only spare (false)",
                        "name": "fitted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Devices currently on this vehicle",
                        "name": "vehicleId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device id prefix",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []services.TrackerView, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "Register a device",
                "parameters": [
                    {
                        "description": "Device; kind gps (deviceId = 15-digit IMEI) or dashcam",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.TrackerInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.TrackerView"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/trackers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "Get a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.TrackerView"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "kind and deviceId are immutable (409).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "Edit a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Changed fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.TrackerInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.TrackerView"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Refused (409) while fitted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "Retire a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trackers/{id}/assignments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "A device's fitting history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.TrackerAssignment"
                            }
                        }
                    }
                }
            }
        },
        "/trackers/{id}/fit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Closes the device's previous fitting and the vehicle's previous device of the same kind, opens the new one, and for GPS sets the vehicle's trackerId — one operation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "Fit a device to a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vehicle and fitting details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.FitInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.TrackerAssignment"
                        }
                    }
                }
            }
        },
        "/trackers/{id}/unfit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trackers"
                ],
                "summary": "Unfit a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "unfittedAt, default now",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.UnfitInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trucks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "List the company's trucks",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only trucks free for assignment",
                        "name": "isAvailable",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort, e.g. name:asc",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filters as field:value, comma separated",
                        "name": "filtered",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []models.Vehicle, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trucks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "Get a truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Vehicle"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/vehicles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "List vehicles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only vehicles free for assignment",
                        "name": "isAvailable",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Members of this vehicle group",
                        "name": "groupId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Plate or chassis prefix",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []services.VehicleView, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Add a vehicle",
                "parameters": [
                    {
                        "description": "Vehicle",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.VehicleInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.VehicleView"
                        }
                    }
                }
            }
        },
        "/vehicles/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Get a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.VehicleView"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Edit a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Changed fields; currentDriverId ” releases the driver",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.VehicleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.VehicleView"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Refused (409) while a device is fitted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Retire a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/warehouses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "List the company's sites",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort, e.g. name:asc",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filters as field:value, comma separated",
                        "name": "filtered",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []models.Site, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Add a site",
                "parameters": [
                    {
                        "description": "Site",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.warehouseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Site"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/warehouses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Get a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Site"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Edit a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Site",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.warehouseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Site"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Retire a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_karlo_masterdata-service_internal_models.Document": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "docType": {
                    "type": "string"
                },
                "driverId": {
                    "type": "string"
                },
                "expiresOn": {
                    "type": "string"
                },
                "fileKey": {
                    "description": "The object-store key, never a URL: a signed URL expires, so a stored one\nrots. The key is resolved to a fresh URL when someone asks to see it.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "issuedOn": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "vehicleId": {
                    "description": "Exactly one owner: a vehicle (STNK, KIR, insurance) or a driver (SIM,\nKTP, medical). VehicleID was the only owner once, so it stays a plain\nstring; empty means \"not a vehicle document\".",
                    "type": "string"
                },
                "verifiedByUserId": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.Driver": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "employeeNo": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "licenseClass": {
                    "type": "string"
                },
                "licenseExpiry": {
                    "description": "LicenseExpiry is a date; stored at UTC midnight, no time is meaningful.",
                    "type": "string"
                },
                "licenseNo": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "description": "Status is active or inactive. Retirement is Deleted, like everywhere.",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "description": "UserID is the auth user when this person has a login. Absent — not\nnull — when nobody has looked: an import cannot assert there is no\naccount, only that it did not link one.",
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.GeoPoint": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "description": "Longitude FIRST, then latitude. GeoJSON's order is the reverse of how\ncoordinates are usually spoken, and getting it wrong puts an Indonesian\nsite in the Indian Ocean without any error.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.Site": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "What the geocoder returned, stored so the lookup happens once rather than\non every read — and because a coordinate alone cannot be shown to a\ndriver or printed on a document.\nCity and province are NAMES, not ids into a region table. There is no\nregion table, and an id referencing nothing is worse than the name it\nstands for: it cannot be read, printed or searched without a lookup that\ndoes not exist.",
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "city": {
                    "type": "string"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "customerCompanyId": {
                    "description": "CustomerCompanyID says whose site this is when a transporter keeps\nits customers' warehouses in its own register (MyWarehouse groups\nthem per customer). Empty for the company's own sites.",
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "geofenceRadiusM": {
                    "description": "How close counts as \"arrived\". Per site, because a roadside drop needs a\nwider radius than a fenced yard.",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "location": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.GeoPoint"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "picUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "postcode": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sitePicPhone": {
                    "description": "Who to call at the gate — the person in charge of this site, not the\ncompany switchboard.",
                    "type": "string"
                },
                "siteType": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.SiteType"
                },
                "street": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.SiteType": {
            "type": "string",
            "enum": [
                "warehouse",
                "depot",
                "port",
                "customer",
                "other"
            ],
            "x-enum-comments": {
                "SiteDepot": "where a transporter keeps its fleet",
                "SitePort": "a sea or dry port",
                "SiteWarehouse": "a loading or unloading point on an order"
            },
            "x-enum-descriptions": [
                "a loading or unloading point on an order",
                "where a transporter keeps its fleet",
                "a sea or dry port",
                "",
                ""
            ],
            "x-enum-varnames": [
                "SiteWarehouse",
                "SiteDepot",
                "SitePort",
                "SiteCustomer",
                "SiteOther"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.TrackerAssignment": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deviceId": {
                    "type": "string"
                },
                "fittedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imei": {
                    "type": "string"
                },
                "installNotes": {
                    "type": "string"
                },
                "installPhotoKey": {
                    "description": "Proof the installation actually happened.\n\nFitting is done in a yard, often by a subcontractor, and \"was this really\ninstalled\" is the first question when a device never reports. A photo\ntaken at the time answers it. An object-store key, never a URL — a signed\nURL expires, so a stored one rots.",
                    "type": "string"
                },
                "installedByUserId": {
                    "type": "string"
                },
                "kind": {
                    "description": "What was fitted, copied from the device so the history outlives the\ndevice document. Kind and DeviceID always; IMEI for GPS devices only,\nbecause telemetry is keyed on it.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.TrackerKind"
                        }
                    ]
                },
                "trackerId": {
                    "description": "Nil once the device document is deleted. The copied IMEI below is what\nstill identifies it — which is the whole reason the IMEI is duplicated\nhere rather than joined from the tracker.",
                    "type": "string"
                },
                "unfittedAt": {
                    "type": "string"
                },
                "vehicleId": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.TrackerKind": {
            "type": "string",
            "enum": [
                "gps",
                "dashcam"
            ],
            "x-enum-varnames": [
                "TrackerGPS",
                "TrackerDashcam"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.TrackerOwner": {
            "type": "string",
            "enum": [
                "karlo",
                "customer",
                "vendor"
            ],
            "x-enum-varnames": [
                "OwnerKarlo",
                "OwnerCustomer",
                "OwnerVendor"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.UnitType": {
            "type": "string",
            "enum": [
                "rigid",
                "head",
                "body"
            ],
            "x-enum-varnames": [
                "UnitRigid",
                "UnitHead",
                "UnitBody"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.Vehicle": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "brandId": {
                    "type": "string"
                },
                "chassisNumber": {
                    "description": "The numbers that identify the PHYSICAL vehicle rather than its\nregistration. A plate is reissued when a vehicle is sold; these are not,\nwhich is why the chassis number is unique everywhere and the plate only\nwithin a company.",
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentDriverId": {
                    "description": "CurrentDriverID is the drivers document; CurrentDriverUserID is that\ndriver's auth user, copied from the document when they have a login.\nBoth are written by the same assignment path; the second stays because\nbusiness-service's dispatch reads driver ids as auth users and a\ndriver with no login must contribute nothing there.",
                    "type": "string"
                },
                "currentDriverUserId": {
                    "type": "string"
                },
                "engineNumber": {
                    "type": "string"
                },
                "fuelRatioKmpl": {
                    "type": "number"
                },
                "fuelTankLiters": {
                    "type": "number"
                },
                "hourmeterHours": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "isAvailable": {
                    "description": "TMS asks this before assigning a load; FMS does not care.",
                    "type": "boolean"
                },
                "licensePlate": {
                    "description": "What everyone calls the truck, exactly as the operator typed it.",
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "odometerKm": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "trackerId": {
                    "description": "TrackerID is a COPY of the live tracker assignment, kept so \"which device\nis on this vehicle\" does not need a query over history.\n\nNothing in MongoDB keeps it in step. In PostgreSQL a trigger did; here\nevery writer must, and a writer that forgets shows a device on the wrong\ntruck. Use the tracker repository's fitting methods rather than setting\nthis directly.",
                    "type": "string"
                },
                "truckBodyId": {
                    "type": "string"
                },
                "truckGroupId": {
                    "description": "TruckGroupID is the vehicle group (vehicle_groups) this unit belongs\nto — one, since FMS's fleet group is single-valued and the two products\nshare the field (Truck.truck_group_id on the wire).",
                    "type": "string"
                },
                "truckHeadId": {
                    "description": "A head names a head type; a body or a rigid names a body type. Both\nfields rather than one, because a rigid truck has a body and no separate\nhead — forcing them through one field would mean guessing which list an\nid belongs to.",
                    "type": "string"
                },
                "unitType": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.UnitType"
                },
                "unitYear": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.DocumentInput": {
            "type": "object",
            "properties": {
                "docType": {
                    "type": "string"
                },
                "driverId": {
                    "type": "string"
                },
                "expiresOn": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "fileKey": {
                    "type": "string"
                },
                "issuedOn": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "vehicleId": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.DriverInput": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "employeeNo": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "licenseClass": {
                    "type": "string"
                },
                "licenseExpiry": {
                    "description": "YYYY-MM-DD; \"\" clears",
                    "type": "string"
                },
                "licenseNo": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.DriverRef": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.FitInput": {
            "type": "object",
            "properties": {
                "fittedAt": {
                    "type": "string"
                },
                "installNotes": {
                    "type": "string"
                },
                "installPhotoKey": {
                    "type": "string"
                },
                "installedByUserId": {
                    "type": "string"
                },
                "vehicleId": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.TrackerInput": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "companyId": {
                    "description": "CompanyID moves a device between Karlo's stock and a company (or\nbetween companies). Platform staff only; ignored for everyone else.\nThis is how the backfilled stock is handed to the companies that\nactually run the devices.",
                    "type": "string"
                },
                "deviceId": {
                    "type": "string"
                },
                "iccid": {
                    "type": "string"
                },
                "imei": {
                    "description": "accepted as an alias of deviceId for gps",
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "modelId": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "ownerName": {
                    "type": "string"
                },
                "phoneNo": {
                    "type": "string"
                },
                "simProvider": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.TrackerRef": {
            "type": "object",
            "properties": {
                "deviceId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.TrackerView": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "companyId": {
                    "description": "Where the device is DEPLOYED. Nil while it sits in Karlo's stock, which\nis why this is optional when nearly every other CompanyID is not.",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentVehicleId": {
                    "type": "string"
                },
                "deviceId": {
                    "description": "DeviceID is the device's identity within its kind — the IMEI for a\nGPS tracker, the vendor's device id for a dashcam — and it is GLOBAL:\ntwo companies cannot hold the same physical device, and a duplicate\nmeans one vehicle's telemetry appearing on another's map.",
                    "type": "string"
                },
                "fittedAt": {
                    "type": "string"
                },
                "iccid": {
                    "description": "The SIM card itself. Survives the number changing, which a phone number\ndoes not — a number is reassigned, an ICCID identifies the card.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imei": {
                    "description": "IMEI is kept for GPS trackers, equal to DeviceID, because every\ntelemetry reading and assignment is keyed on it. Empty for a dashcam.",
                    "type": "string"
                },
                "kind": {
                    "description": "Kind is what the device is: a GPS tracker or a dashcam. One register,\nbecause both are a physical device fitted to a vehicle with a fitting\nhistory, and two registers is how one vehicle ends up with a device\nin each that nobody can see together.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.TrackerKind"
                        }
                    ]
                },
                "modelId": {
                    "description": "The model, always by reference. A free-text name sat beside this for\ndevices not yet catalogued, and it was the wrong answer: two spellings of\none model cannot be compared, so \"every device of this model\" — the\nquestion asked when a firmware fault appears — would miss half of them.",
                    "type": "string"
                },
                "owner": {
                    "description": "Who OWNS it — a different question from where it is, and the two differ\nconstantly. Without the distinction nobody can answer \"which of our units\nare out with customers\" or \"who do we chase when this one fails\".",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.TrackerOwner"
                        }
                    ]
                },
                "ownerName": {
                    "type": "string"
                },
                "phoneNo": {
                    "description": "PhoneNo is the SIM's MSISDN — how the device is reached for SMS\ncommands. FMS keeps it per device; kept here so the two agree.",
                    "type": "string"
                },
                "simProvider": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.UnfitInput": {
            "type": "object",
            "properties": {
                "unfittedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.VehicleInput": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "brandId": {
                    "type": "string"
                },
                "chassisNumber": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "currentDriverId": {
                    "type": "string"
                },
                "engineNumber": {
                    "type": "string"
                },
                "fuelRatioKmpl": {
                    "type": "number"
                },
                "fuelTankLiters": {
                    "type": "number"
                },
                "hourmeterHours": {
                    "type": "number"
                },
                "isAvailable": {
                    "type": "boolean"
                },
                "licensePlate": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "odometerKm": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "truckBodyId": {
                    "type": "string"
                },
                "truckGroupId": {
                    "type": "string"
                },
                "truckHeadId": {
                    "type": "string"
                },
                "unitType": {
                    "type": "string"
                },
                "unitYear": {
                    "type": "integer"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_services.VehicleView": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "brandId": {
                    "type": "string"
                },
                "chassisNumber": {
                    "description": "The numbers that identify the PHYSICAL vehicle rather than its\nregistration. A plate is reissued when a vehicle is sold; these are not,\nwhich is why the chassis number is unique everywhere and the plate only\nwithin a company.",
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentDriverId": {
                    "description": "CurrentDriverID is the drivers document; CurrentDriverUserID is that\ndriver's auth user, copied from the document when they have a login.\nBoth are written by the same assignment path; the second stays because\nbusiness-service's dispatch reads driver ids as auth users and a\ndriver with no login must contribute nothing there.",
                    "type": "string"
                },
                "currentDriverUserId": {
                    "type": "string"
                },
                "driver": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.DriverRef"
                },
                "engineNumber": {
                    "type": "string"
                },
                "fuelRatioKmpl": {
                    "type": "number"
                },
                "fuelTankLiters": {
                    "type": "number"
                },
                "hourmeterHours": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "isAvailable": {
                    "description": "TMS asks this before assigning a load; FMS does not care.",
                    "type": "boolean"
                },
                "licensePlate": {
                    "description": "What everyone calls the truck, exactly as the operator typed it.",
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "odometerKm": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "tracker": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_services.TrackerRef"
                },
                "trackerId": {
                    "description": "TrackerID is a COPY of the live tracker assignment, kept so \"which device\nis on this vehicle\" does not need a query over history.\n\nNothing in MongoDB keeps it in step. In PostgreSQL a trigger did; here\nevery writer must, and a writer that forgets shows a device on the wrong\ntruck. Use the tracker repository's fitting methods rather than setting\nthis directly.",
                    "type": "string"
                },
                "truckBodyId": {
                    "type": "string"
                },
                "truckGroupId": {
                    "description": "TruckGroupID is the vehicle group (vehicle_groups) this unit belongs\nto — one, since FMS's fleet group is single-valued and the two products\nshare the field (Truck.truck_group_id on the wire).",
                    "type": "string"
                },
                "truckHeadId": {
                    "description": "A head names a head type; a body or a rigid names a body type. Both\nfields rather than one, because a rigid truck has a body and no separate\nhead — forcing them through one field would mean guessing which list an\nid belongs to.",
                    "type": "string"
                },
                "unitType": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.UnitType"
                },
                "unitYear": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.errorBody": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Entry not found."
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_handlers.kindInfo": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "shareable": {
                    "description": "Shareable is false for a catalogue whose entries always belong to one\ncompany — a vehicle group, an item. Sent so a staff form offers \"shared\nwith everyone\" only where that is possible.",
                    "type": "boolean"
                },
                "writable": {
                    "description": "Writable is false for a catalogue that can be read and not edited. Sent\nso the UI can omit the add button rather than offering one that fails.",
                    "type": "boolean"
                }
            }
        },
        "internal_handlers.warehouseRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "customerCompanyId": {
                    "description": "The customer this site belongs to (MyWarehouse groups per customer).",
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "geofenceRadiusMeters": {
                    "type": "integer"
                },
                "latitude": {
                    "description": "Pointers, so \"not supplied\" stays distinct from zero. Nought, nought is\na real place and the service refuses it; a nil pair means the site has\nno coordinate yet, which is allowed.",
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "picName": {
                    "type": "string"
                },
                "picPhone": {
                    "type": "string"
                },
                "postcode": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "siteType": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "RS256 access token issued by the authentication service, as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5002",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Karlo Master Data API",
	Description:      "Reference data. Global catalogues (brands, truck types, cargo types, items, tracker models) shared by every company, and per-company registers (customers, vehicle groups, trucks, warehouses).\\n\\nEvery endpoint needs a bearer token from the authentication service. Karlo staff may act for a client by sending X-Acting-For: <companyId>.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
