// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Karlo Engineering",
            "email": "engineering@karlo.co.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalog": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Catalogue kinds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers.kindInfo"
                            }
                        }
                    }
                }
            }
        },
        "/catalog/{kind}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List one catalogue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Restrict to children of this entry (e.g. sub-categories of a category)",
                        "name": "parentId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort, e.g. name:asc",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filters as field:value, comma separated",
                        "name": "filtered",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data[], meta{page,limit,totalRows,totalPages}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Karlo staff create shared entries; a company creates its own. Fields depend on the kind — see the models for each catalogue (Brand, CargoType, Item, TruckHead, TruckBody, TruckClass, Customer, VehicleGroup, TrackerModel…).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Add a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind, from GET /catalog",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entry fields for the kind",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/catalog/{kind}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Edit a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Changed fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft: documents already referencing it keep resolving; the name frees up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Retire a catalogue entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Catalogue kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/trucks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "List the company's trucks",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only trucks free for assignment",
                        "name": "isAvailable",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort, e.g. name:asc",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filters as field:value, comma separated",
                        "name": "filtered",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []models.Vehicle, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trucks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet"
                ],
                "summary": "Get a truck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Truck id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Vehicle"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/warehouses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "List the company's sites",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zero-based page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rows per page",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort, e.g. name:asc",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filters as field:value, comma separated",
                        "name": "filtered",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success, data []models.Site, meta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Add a site",
                "parameters": [
                    {
                        "description": "Site",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.warehouseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Site"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        },
        "/warehouses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Get a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Site"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Edit a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Site",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.warehouseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.Site"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Retire a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.errorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_karlo_masterdata-service_internal_models.GeoPoint": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "description": "Longitude FIRST, then latitude. GeoJSON's order is the reverse of how\ncoordinates are usually spoken, and getting it wrong puts an Indonesian\nsite in the Indian Ocean without any error.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.Site": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "What the geocoder returned, stored so the lookup happens once rather than\non every read — and because a coordinate alone cannot be shown to a\ndriver or printed on a document.\nCity and province are NAMES, not ids into a region table. There is no\nregion table, and an id referencing nothing is worse than the name it\nstands for: it cannot be read, printed or searched without a lookup that\ndoes not exist.",
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "city": {
                    "type": "string"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "geofenceRadiusM": {
                    "description": "How close counts as \"arrived\". Per site, because a roadside drop needs a\nwider radius than a fenced yard.",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "location": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.GeoPoint"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "picUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "postcode": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sitePicPhone": {
                    "description": "Who to call at the gate — the person in charge of this site, not the\ncompany switchboard.",
                    "type": "string"
                },
                "siteType": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.SiteType"
                },
                "street": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_masterdata-service_internal_models.SiteType": {
            "type": "string",
            "enum": [
                "warehouse",
                "depot",
                "port",
                "customer",
                "other"
            ],
            "x-enum-comments": {
                "SiteDepot": "where a transporter keeps its fleet",
                "SitePort": "a sea or dry port",
                "SiteWarehouse": "a loading or unloading point on an order"
            },
            "x-enum-descriptions": [
                "a loading or unloading point on an order",
                "where a transporter keeps its fleet",
                "a sea or dry port",
                "",
                ""
            ],
            "x-enum-varnames": [
                "SiteWarehouse",
                "SiteDepot",
                "SitePort",
                "SiteCustomer",
                "SiteOther"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.UnitType": {
            "type": "string",
            "enum": [
                "rigid",
                "head",
                "body"
            ],
            "x-enum-varnames": [
                "UnitRigid",
                "UnitHead",
                "UnitBody"
            ]
        },
        "github_com_karlo_masterdata-service_internal_models.Vehicle": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "brandId": {
                    "type": "string"
                },
                "chassisNumber": {
                    "description": "The numbers that identify the PHYSICAL vehicle rather than its\nregistration. A plate is reissued when a vehicle is sold; these are not,\nwhich is why the chassis number is unique everywhere and the plate only\nwithin a company.",
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentDriverUserId": {
                    "type": "string"
                },
                "engineNumber": {
                    "type": "string"
                },
                "fuelRatioKmpl": {
                    "type": "number"
                },
                "fuelTankLiters": {
                    "type": "number"
                },
                "hourmeterHours": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "isAvailable": {
                    "description": "TMS asks this before assigning a load; FMS does not care.",
                    "type": "boolean"
                },
                "licensePlate": {
                    "description": "What everyone calls the truck, exactly as the operator typed it.",
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "odometerKm": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "trackerId": {
                    "description": "TrackerID is a COPY of the live tracker assignment, kept so \"which device\nis on this vehicle\" does not need a query over history.\n\nNothing in MongoDB keeps it in step. In PostgreSQL a trigger did; here\nevery writer must, and a writer that forgets shows a device on the wrong\ntruck. Use the tracker repository's fitting methods rather than setting\nthis directly.",
                    "type": "string"
                },
                "truckBodyId": {
                    "type": "string"
                },
                "truckHeadId": {
                    "description": "A head names a head type; a body or a rigid names a body type. Both\nfields rather than one, because a rigid truck has a body and no separate\nhead — forcing them through one field would mean guessing which list an\nid belongs to.",
                    "type": "string"
                },
                "unitType": {
                    "$ref": "#/definitions/github_com_karlo_masterdata-service_internal_models.UnitType"
                },
                "unitYear": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.errorBody": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Entry not found."
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_handlers.kindInfo": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "shareable": {
                    "description": "Shareable is false for a catalogue whose entries always belong to one\ncompany — a vehicle group, an item. Sent so a staff form offers \"shared\nwith everyone\" only where that is possible.",
                    "type": "boolean"
                },
                "writable": {
                    "description": "Writable is false for a catalogue that can be read and not edited. Sent\nso the UI can omit the add button rather than offering one that fails.",
                    "type": "boolean"
                }
            }
        },
        "internal_handlers.warehouseRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "geofenceRadiusMeters": {
                    "type": "integer"
                },
                "latitude": {
                    "description": "Pointers, so \"not supplied\" stays distinct from zero. Nought, nought is\na real place and the service refuses it; a nil pair means the site has\nno coordinate yet, which is allowed.",
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "picName": {
                    "type": "string"
                },
                "picPhone": {
                    "type": "string"
                },
                "postcode": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "siteType": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "RS256 access token issued by the authentication service, as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5002",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Karlo Master Data API",
	Description:      "Reference data. Global catalogues (brands, truck types, cargo types, items, tracker models) shared by every company, and per-company registers (customers, vehicle groups, trucks, warehouses).\\n\\nEvery endpoint needs a bearer token from the authentication service. Karlo staff may act for a client by sending X-Acting-For: <companyId>.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
